services:
  - type: web
    name: ergonometapp
    runtime: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
    plan: free
